[package]
name = "korangar-gameplay"
version = "0.1.0"
edition = "2024"

[dependencies]
korangar-interface = { workspace = true, optional = true }
ragnarok-packets = { workspace = true }
rust-state = { workspace = true, optional = true }

[features]
interface = ["korangar-interface", "rust-state"]
